### PR TITLE
Add support for multiple SMTP transactions per connection.

### LINKED ISSUE #21: Sometimes emails arrive to wrong email boxes
cc @jrgm @rfk 

See http://restmail.net/mail/pushtest

image

`signin0.7721520143095404%40restmail.net` arrived to the `pushtest` mailbox

@jrgm has more information on this. Seems like a bug in restmail updates

### PR DESCRIPTION
**Pull request by rfk**
This hopefully fixes #21 by adding support for more SMTP stuff that might be seen in the wild, including:

* Multiple transactions done on a single connection
* NOOP commands
* RSET commands (which I haven't seen i the wild, but seemed pretty easy and in line with the rest of the changes)

@vladikoff @jrgm r?

### CODE REVIEW

**Comment by jrgm** [comment]
So, this is running on restmail.net now. Seems to work okay, but not sure if it is handling every case; there was a test failure complaining about an unexpected email address. I have ngrep logging everything now, and can look into any future failures. 

One suggestion: the log message is pretty verbose now. Perhaps something in the middle between everything and barely anything, like this - https://gist.github.com/jrgm/f830c768a2774e638a575192c74d10b4

**Comment by jrgm** [comment]
Otherwise, r+

**Comment by rfk** [comment]
>  the log message is pretty verbose now. 

Whoops, I think I accidentally left that extra logging of the mail message in there unintentionally.

**Comment by rfk** [comment]
@jrgm would you prefer to see your suggested summary info, or just revert to showing nothing about the email like it was previously?

**Comment by jrgm** [comment]
> @jrgm would you prefer to see your suggested summary info, or just revert to showing nothing about the email like it was previously?

I think I prefer my suggested summary info. Gives something to debug with, without being overwhelming.

**Comment by rfk** [comment]
thanks @jrgm, I've added your change and will merge assuming travis goes green

**Pull request merged**
